### ISSUE TITLE
Autocomplete Only

### ISSUE THREAD

**Issue by kisuka** [sliptree/bootstrap-tokenfield#118]
Any way we could get a feature where you could only select autocomplete options to be made as tags? So that you can't create ones by: comma, enter, paste.

Paste would need to change to searching the autocomplete options instead of createtokenfrominput.

By autocomplete, I mean the options from autocomplete and typeahead.

**Comment by jwillmer** [comment]
would also be interessted in an implementation of this (not a workaround)
