### ISSUE TITLE
Remove all tokens

### ISSUE THREAD

**Issue by asacarter** [sliptree/bootstrap-tokenfield#133]
Is there a method to simply remove all tokens without having to destroy and re-initialize?

`$('#myField').tokenfield('setTokens', '');` does not work.

**Comment by fzembow** [comment]
`$('#myField').tokenfield('setTokens', '');` no longer works again using the latest version ...

**Comment by aelor** [comment]
+1 doesn't work

**Comment by Kalpen** [comment]
still it doesn't work.

**Comment by mehmood-memon** [comment]
I got a hack. We can do it by two lines.

`$('#myField').tokenfield('setTokens', []);`
`$('#myField').val('');`

The first line will remove all **tokens only**, and the second line will remove the values from the **text field**.

**Comment by JoshuaJiangFD** [comment]
+1 doesn't work

**Comment by nopphawitKar** [comment]
$('#myField').tokenfield('setTokens', []); <-- this one work
$('#myField').val(''); <-- but this one doesn't
Can someone help me to remove text from tokenfield?

**Comment by mehmood-memon** [comment]
@nopphawitKar ! The second line is just to blank the text field. Make sure that its name is same as your text field. You can inspect it using debugger or inspect tool.

**Comment by marooj** [comment]
// Destroy on click
				$('#destroy').on('click', function() {
					$('.tokenfield').removeAttr('data-fouc').tokenfield('destroy');
					$('.tokenfield').tokenfield({
					autocomplete: {
						source: sourceDataObj,
						delay: 100
					},
					showAutocompleteOnFocus: true
					});
				});
