### ISSUE TITLE
Tell typeahead all the tags

### ISSUE THREAD

**Issue by agladysh** [sliptree/bootstrap-tokenfield#209]
I need an advanced typeahead logic, where I change the suggestions depending on the existing tokens. 

Synthetic example (user input to possible suggestions):

* fruits: red, yellow, apples, oranges, cherries, apricots, ferraries
* fruits red: apples, cherries
* fruits yellow: oranges, apricots
* red: apples, cherries, ferraries

I.e. if the query string contains words "fruits" and "yellow", only yellow fruits should appear in the suggestions.

Now typeahead only sees the word the user is typing now.

Is there a way I could make the whole query available to the typeahead without hacking the tokenfield sources?

**Comment by kamilgrzegorczyk** [comment]
You can access currently seelcted tokens anytime by using 

```javascript
$('#myField').tokenfield('getTokens');

**Comment by agladysh** [comment]
OK, this will work for me, thanks!
