### ISSUE TITLE
Improper input field resizing on window resize

### ISSUE THREAD

**Issue by kamilgrzegorczyk** [sliptree/bootstrap-tokenfield#211]
Whenever browser window is being resized input field calculates all available space for it to adjust its width properly. 

It works fine until input field drops itself to the second line. Then on any calculations performed field "assumes" that it has all available space and it never goes back to first row, even if there is plenty of space.

![screen shot 2015-03-04 at 16 32 33](https://cloud.githubusercontent.com/assets/665560/6486728/2ab72194-c28d-11e4-8ce6-a88d7c8117a2.png)

**Comment by Manu789** [comment]
This issue appears also on initialization. When I add or remove a tag or resize the browser window then the width of the input field is fixed.
I use it with bootstrap 3.3.2 and in an horizontal form.
