### ISSUE TITLE
want to call user-defined function on blur of tokenfield

### ISSUE THREAD

**Issue by vijay52** [sliptree/bootstrap-tokenfield#220]
When tokenfield is blur i want to call a function which checks the tokens enterd, but I can't do it, on blur is not working on it.??  Suggestions might be helpful in this?

**Comment by kamilgrzegorczyk** [comment]
you can do it like this:

```javascript
inputField.data('bs.tokenfield').on('blur', function(){
 //your code here
});
```

**Comment by vijay52** [comment]
Working fine. ..

$('#tokenfield').data('bs.tokenfield').$input.on('blur', function(){
 //your code here
});

Thanks...

**Comment by Lozzi** [comment]
I have a similar problem, where I activate the blur event like so:
```js
$(element).siblings( '.token-input' ).blur( blur );
```
The event however fires when I press the arrow keys, when I press backspace and when I click outside of the tokenfield, I would only like it to activate when esc is pressed or a user clicks outside of the tokenfield.

Any suggestions?
