### ISSUE TITLE
Chrome warning at console: 'getMatchedCSSRules()' is deprecated.

### ISSUE THREAD

**Issue by Cow258** [sliptree/bootstrap-tokenfield#255]
Chrome version: 45.0.2454.85 m
Warning message:
'getMatchedCSSRules()' is deprecated. For more help, check https://code.google.com/p/chromium/issues/detail?id=437569#c2

**Comment by TheKoon** [comment]
this plugin is dead man :skull:

**Comment by abdalafer** [comment]
Would be great if there was a message stating that its not longer supported, unless I missed it. 
What are people using now days in replacement for this plugin?

**Comment by jekuno** [comment]
I still use this plugin as it fits my needs (even though there are issues).
Regarding maintenance have a look at https://github.com/sliptree/bootstrap-tokenfield/issues/203

**Comment by devmi** [comment]
You may be interested at [this fix](https://github.com/Open-Xchange-Frontend/bootstrap-tokenfield/commit/a7f25abb631d5ad05ba24ad1c4ef42e60c51f13a#diff-797459841415151e5385ad5ed02ecb6f)
