### ISSUE TITLE
Duplicated text still display and submit

### ISSUE THREAD

**Issue by ethancfchen** [sliptree/bootstrap-tokenfield#267]
When I type a duplicated text, it still show on the input box like
![error](https://cloud.githubusercontent.com/assets/5051791/12708476/cda0fd7c-c8da-11e5-8f94-31a85ea2f1e1.png)
then when I click the submit button, it will be send.
I tried

``` javascript
$('input').tokenfield('getTokensList')
```

and

``` javascript
$('input').val()
```

it will get the same values.

Why not just like the [Bootstrap Tags Input](http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/), when user tape a duplicated text, it will show a hint on the tag.

**Comment by devmi** [comment]
You may want to look at this [example](https://github.com/sliptree/bootstrap-tokenfield#how-can-i-prevent-duplicate-tokens-from-being-entered)

**Comment by ethancfchen** [comment]
Looks like this project has been abandoned.
