### ISSUE TITLE
TypeError: this.$input.autocomplete is not a function

### ISSUE THREAD

**Issue by ppazos** [sliptree/bootstrap-tokenfield#326]
I'm trying the plugin with Bootstrap 4 and jQuery 3.2.1 and this config:

```
$('#tags').tokenfield({
           autocomplete: {
             source: ['red','blue','green','yellow','violet','brown','purple','black','white'],
             delay: 100
           },
           showAutocompleteOnFocus: true
         });
```

The tag input seems to work OK but I got that error on the console about the autocomplete.

**Comment by MoaMoaK** [comment]
hey, was just passing by to see if someone had the same problem as I do. And yes I found you but no answer (*sad*).
But fortunately, I did found a solution in my case at least : I just had to add [jquery-ui ](http://jqueryui.com/) in the HTML. It's quickly evoked somewhere in the docs but clearly not enough.
I hope that will help you.

**Comment by ppazos** [comment]
+1

**Comment by sogani02** [comment]
+1

**Comment by pedropamn** [comment]
+1
